### ISSUE TITLE
Latexmk issue within Conda Env

### ISSUE THREAD

**Issue by tonino0013** [GjjvdBurg/labella.py#17] opened 2022-01-10 23:39 UTC
Dear all,

I just tried to run the examples from `https://github.com/GjjvdBurg/labella.py/blob/master/examples/timeline_kit_1.py`
I installed within conda enviorement the `latexmk`, I tested with:

```
from labella.tex import text_dimensions
text_dimensions("foo", silent=False)
#___output___#


Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Director\anaconda3\envs\allinone\lib\site-packages\labella\tex.py", line 140, in text_dimensions
    latexmk_options=latexmk_options)
  File "C:\Users\Director\anaconda3\envs\allinone\lib\site-packages\labella\tex.py", line 106, in get_latex_dims
    compile_latex(fname, tmpdirname, latexmk_options, silent=silent)
  File "C:\Users\Director\anaconda3\envs\allinone\lib\site-packages\labella\tex.py", line 91, in compile_latex
    raise (e)
  File "C:\Users\Director\anaconda3\envs\allinone\lib\site-packages\labella\tex.py", line 89, in compile_latex
    output = subprocess.check_output(command, stderr=subprocess.STDOUT)
  File "C:\Users\Director\anaconda3\envs\allinone\lib\subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "C:\Users\Director\anaconda3\envs\allinone\lib\subprocess.py", line 488, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\Director\anaconda3\envs\allinone\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "C:\Users\Director\anaconda3\envs\allinone\lib\subprocess.py", line 1207, in _execute_child
    startupinfo)
[WinError 2] The system cannot find the file specified

```
This is the same error as [(https://github.com/GjjvdBurg/labella.py/issues/14)]

Does anyone have the same issue?
Stay safe and best regards,
Tonino

**Comment by GjjvdBurg** [comment] 2022-01-11 12:45
Hi Tonino, thanks for raising this issue, I'm sorry to hear you're having trouble with the package. The problem seems to be that the ``latexmk`` can't be found. One thing to try is to run ``latexmk`` in the conda environment to see if that works. If that works, then running labella in the same directory (with the conda environment activated) should work as well. Please let me know if that solves your issue or whether you need further assistance.

**Comment by tonino0013** [comment] 2022-01-11 13:35
Dear @GjjvdBurg ,
I type;
`latexmk`, result:
```
Latexmk: This is Latexmk, John Collins, 17 Jan. 2018, version: 4.55.

Latexmk: No file name specified, and I couldn't find any
Use
   latexmk -help
to get usage information


```
and then `latexmk -h` and I got the help menu.
I installaed latexmk within conda, so where can I find the path for latex?, or Do I have to add to enviorement variables?

Stay safe and best regards,
Tonino

**Comment by GjjvdBurg** [comment] 2022-01-11 18:17
Hi Tonino,

Thanks for confirming that latexmk works in the conda environment. Just to
cover the basics, you have installed labella in the same conda environment
and are running the examples with the environment activated?

**Comment by tonino0013** [comment] 2022-01-11 19:39
Dear @GjjvdBurg ,
I work with virtual enviorement activated, `labella` is installed in the same enviorement that `latxmk`.
Here I list yhe packages on my enviorement, `labella` is included.
[list_env.csv](https://github.com/GjjvdBurg/labella.py/files/7849471/list_env.csv)

**Comment by GjjvdBurg** [comment] 2022-01-13 00:33
Thanks for the package list @tonino0013. This is a bit difficult to debug as it seems that while LatexMk is installed, it can't be found from Python. Can you try the following in the conda environment? This looks only at the ``compile_latex`` function, which might help narrowing down what goes wrong:

```python
from labella.tex import compile_latex
with open('./test.tex', 'w') as fp:
    fp.write("""\
\\documentclass{article}
\\begin{document}
Hello, world!
\\end{document}""")
compile_latex('./test.tex', '.', None, silent=False)
```

(on my system this produces a ``test.pdf`` file in the current directory.)

**Comment by tonino0013** [comment] 2022-01-13 01:13
Hi @GjjvdBurg,
Thanks for the time. I run the code, however I got the following:
```
File "C:\Users\Director\AppData\Local\Temp/ipykernel_14880/463237626.py", line 1, in <module>
    compile_latex(r'D:\Inves\Pdoc\Timeline\test.tex', '.', None, silent=False)

  File "C:\Users\Director\anaconda3\envs\allinone\lib\site-packages\labella\tex.py", line 91, in compile_latex
    raise (e)

  File "C:\Users\Director\anaconda3\envs\allinone\lib\site-packages\labella\tex.py", line 89, in compile_latex
    output = subprocess.check_output(command, stderr=subprocess.STDOUT)

  File "C:\Users\Director\anaconda3\envs\allinone\lib\subprocess.py", line 411, in check_output
    **kwargs).stdout

  File "C:\Users\Director\anaconda3\envs\allinone\lib\subprocess.py", line 488, in run
    with Popen(*popenargs, **kwargs) as process:

  File "C:\Users\Director\anaconda3\envs\allinone\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 108, in __init__
    super(SubprocessPopen, self).__init__(*args, **kwargs)

  File "C:\Users\Director\anaconda3\envs\allinone\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)

  File "C:\Users\Director\anaconda3\envs\allinone\lib\subprocess.py", line 1207, in _execute_child
    startupinfo)
```
I was not able to produce the test.pdf file.
Thank you

**Comment by GjjvdBurg** [comment] 2022-01-13 18:02
Is that the full output that you get? It seems to be missing the actual error

**Comment by tonino0013** [comment] 2022-01-13 22:19
Dear @GjjvdBurg,
Sorry, this is the full error message:

```
Traceback (most recent call last):

  File "C:\Users\Director\AppData\Local\Temp/ipykernel_4796/105075423.py", line 8, in <module>
    compile_latex('./test.tex', '.', None, silent=False)

  File "C:\Users\Director\anaconda3\envs\allinone\lib\site-packages\labella\tex.py", line 91, in compile_latex
    raise (e)

  File "C:\Users\Director\anaconda3\envs\allinone\lib\site-packages\labella\tex.py", line 89, in compile_latex
    output = subprocess.check_output(command, stderr=subprocess.STDOUT)

  File "C:\Users\Director\anaconda3\envs\allinone\lib\subprocess.py", line 411, in check_output
    **kwargs).stdout

  File "C:\Users\Director\anaconda3\envs\allinone\lib\subprocess.py", line 488, in run
    with Popen(*popenargs, **kwargs) as process:

  File "C:\Users\Director\anaconda3\envs\allinone\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 108, in __init__
    super(SubprocessPopen, self).__init__(*args, **kwargs)

  File "C:\Users\Director\anaconda3\envs\allinone\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)

  File "C:\Users\Director\anaconda3\envs\allinone\lib\subprocess.py", line 1207, in _execute_child
    startupinfo)

FileNotFoundError: [WinError 2] The system cannot find the file specified
```
Thanks for the time
Tonino

**Comment by GjjvdBurg** [comment] 2022-01-14 00:27
I don't use anaconda myself, but there seem to be some other issues on Github with similar error messages; do these links help?
```
- https://github.com/jupyter/notebook/issues/4079
- https://github.com/jupyter/notebook/issues/2301
```

I strongly suspect that the issue is with the installation and not with labella.py. Something is causing latexmk to be available outside of Python, but not from Python. The latter you could verify by running:
```python
import subprocess
subprocess.check_output(["latexmk", "-h"])
```

**Comment by tonino0013** [comment] 2022-01-14 04:18
Dear @GjjvdBurg ,
I got the same error that I showed. Let me check the pages you sent me, I will let you kwow, thanks for the time,

**Comment by SeaDude** [comment] 2022-01-25 22:02
What did you find? I am receiving the same error without anaconda. 
I even installed `pip install latexmk.py` in a brand new virtual env. 
Heres the results of `pip freeze > requirements.txt`:
```
intervaltree==3.1.0
labella==0.9.8
latexmk.py==0.4
sortedcontainers==2.4.0
```

**Comment by SeaDude** [comment] 2022-01-26 05:13
@tonino0013, see this documentation: https://github.com/GjjvdBurg/labella.py/issues/14#issuecomment-1021672875
Maybe `latexmk.exe` is not in your `Path` variable.

**Comment by tonino0013** [comment] 2022-01-27 19:11
Dear @SeaDude ,
you have the reason, adding the "MiKTeX" t enviorement variables allowd me to write a pdf file shared by @GjjvdBurg  exmaple.
Thank you

**Comment by GjjvdBurg** [comment] 2022-01-27 22:33
Glad to hear you got it to work @tonino0013 and thanks for the assist @SeaDude! I'll close this as it appears the issue is resolved.

**Closed by GjjvdBurg** 2022-01-27 22:33 UTC
